---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - curl
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - software-properties-common

- name: depends for Ubuntu
  include: "Ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

